# Generated by Django 5.0.6 on 2024-05-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quote",
            old_name="tags",
            new_name="_tags",
        ),
    ]
