# Generated by Django 5.0.6 on 2024-05-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_alter_quote__tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
